- hosts: localserver
  sudo: yes
  tasks:
    - name: Ensure required packages are installed
      apt: name={{item}}
      with_items:
        - python-psycopg2
        - libpq-dev
        - postgresql

    - name: Create a new database with name mazeserver
      postgresql_db: name=mazeserver
